version: "2"
linters:
  enable:
    - bodyclose
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - nilerr
    - prealloc
    - revive
    - unparam
    - whitespace
  settings:
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 50
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - goconst
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
